# Excavator auto-updates this file. Please contribute improvements to the central template.

# This file is intentionally empty. The file's existence enables changelog-app and is empty to use the default configuration.
repo-type:
  type: default
  default:
    changelogDir: changelog
